### ISSUE TITLE
https://github.com/Holidays1999/Neural-Network- Pruning-through-its-RegularGraph-Structure这个怎么找不到了作者大大o(╥﹏╥)o

### ISSUE THREAD

**Issue by hoolyu** [JingyangXiang/OvSW#1]
https://github.com/Holidays1999/Neural-Network- Pruning-through-its-RegularGraph-Structure这个怎么找不到了作者大大o(╥﹏╥)o

**Comment by JingyangXiang** [comment]
Hey, this is our repo: https://github.com/JingyangXiang/Neural-Network-Pruning-through-its-RegularGraph-Structure

**Comment by hoolyu** [comment]
谢谢Thanks♪(･ω･)ﾉ
